name: dtrade
description: "D Trade Capital - Institutional Grade Trading Terminal APP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  google_sign_in: ^6.2.1
  dio: ^5.0.0
  flutter_riverpod: ^2.4.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  go_router: ^12.0.0
  fl_chart: ^0.66.0
  socket_io_client: ^2.0.3
  candlesticks: ^2.1.0
  intl: ^0.19.0
  image_picker: ^1.2.1
  file_picker: ^11.0.2
  google_fonts: ^8.1.0
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpeg
    - assets/images/world_map.png
    - assets/world-map.svg
    - assets/env
